apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-vault-agent-config
  namespace: default
data:
  config-init.hcl: |
    exit_after_auth = true

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
            role = "payments"
        }
      }

      sink = {
        config = {
          path = "/vault/secrets/.token"
        }

        type = "file"
      }
    }
  
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
            role = "payments"
        }
      }
      
      sink = {
        config = {
          path = "/vault/secrets/.token"
        }

        type = "file"
      }
    }

    template {
      destination = "/vault/secrets/config.json"
      contents = <<-EOT
        {
          {{ with secret "database/creds/db-app" -}}
          "db_connection": "postgresql://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/wizard",
          {{- end }}
          {{ with secret "kv2/data/payments" -}}
          "api_key": "{{ .Data.data.api_key }}"
          {{- end }}
        }
      EOT
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-configmap: "payments-vault-agent-config" 
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.25.1