apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payments"
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/db-app"
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.25.1